### ISSUE TITLE
Sentral Status 255 

### ISSUE THREAD

**Issue by jcorbett** [gregtomasch/EM7180_SENtral_Calibration#10]
Is it possible to reset the eeprom? 

I ran the calibration once (I made sure to run the correct version: teensy_inv using teensy 3.6 and mpu9250/bmp280 version sentral), but when attempting to rerun, it looks like the eeprom has been corrupted: 
```
Initializing Sentral_0
Sentral_0:
Scanning...
No I2C devices found

Sentral Status: 255 (Should be 11)

Sentral firmware loaded. Fetching Accel Cal and WS parameters...
```

I connected to a linux device and when set in passthrough mode, I'm no longer seeing the eeprom data or id register on the bus (using i2cdetect). 

Thanks!

**Comment by gregtomasch** [comment]
It looks like something is wrong with the I2C bus; no devices are being detected. Even if the EEPROM is corrupt, I think the EM7180 should still ACK at address 0x28...
