### ISSUE TITLE
Calibration status question on power up

### ISSUE THREAD

**Issue by gerowtj** [gregtomasch/EM7180_SENtral_Calibration#12]
Hi Greg,
After performing the calibration procedure for the magnetometer and saving the warm start parameters (option 2), will the unit show an "Algorithm Status" of "0" or "8" on powerup?

It's currently showing a "0" and after a small bit of movement goes to an "8".  I just want to verify this is normal operation after calibration.

Thanks
Tom

**Comment by gregtomasch** [comment]
This is totally normal,,,
