### ISSUE TITLE
ESP32 with INV USFS does not boot up properly when board not unpowered. 

### ISSUE THREAD

**Issue by josefinHeilig** [gregtomasch/EM7180_SENtral_Calibration#2]
Hi Greg,
we are using the ESP32 with the Invense Sense USFS.
After calibration it works perfectly fine as described. Thanks for the detailed information on how to do that!
It just seems that the sentral doesn't always boot up with the right status while connected to the serial monitor with the ESP32. 

It always works if we unpower the board, but otherwise it does give:
Sentral Status: 3 (Should be 11) 

In the `void EM7180::initSensors()` function there is this part which does not work as expected.

```
// Check SENtral status, make sure EEPROM upload of firmware was accomplished
 STAT = I2C->readByte(EM7180_ADDRESS, EM7180_SentralStatus);
 while(!(STAT & 0x01))
 {
   I2C->writeByte(EM7180_ADDRESS, EM7180_ResetRequest, 0x01);
   delay(500);  
   count++;  
   STAT = I2C->readByte(EM7180_ADDRESS, EM7180_SentralStatus);
   if(count > 100) break;
 }
 #ifdef SERIAL_DEBUG
   Serial.print("Sentral Status: "); 
   Serial.print(STAT);
   Serial.print(" (Should be 11)");
   Serial.println("");
   Serial.println("");
 #endif

```
The while loop is never entered, I tested with a print command inside.
The STAT variable is still reading the old sentral status unless you unpower the board and thus normally the EEUpload Bit is still true.
When you unpower it, then the sentral will jump to the beginning of the initialization code and reinitialize the registers. If you don't, it does not and also doesn't send the reset request as it does not enter the while loop.
I now put the reset request:

```
  I2C->writeByte(EM7180_ADDRESS, EM7180_ResetRequest, 0x01); 
  delay(1000); 
```

before the reading of the Sentral Status and now it is fine. 

Cheers, Katrin

**Comment by gregtomasch** [comment]
Hi Katrin,

This is a good find... Properly resetting the Sentral has been a nagging little issue for a long time; it has been worked-around by power-cycling the entire MCU/IMU combination. I need to test this a bit more to be sure that it doesn't have any other unintended consequences. If it doesn't do anything antisocial, I'll include it...

Best,
Greg
