### ISSUE TITLE
EM7180 hanging on   EM7180::EM7180_set_integer_param (0x49, 0x00)

### ISSUE THREAD

**Issue by emoseman** [gregtomasch/EM7180_SENtral_Calibration#4]
Not sure what else to include.  It is looping endlessly inside that function here:

`while(!(STAT==param))
  {
    STAT = I2C->readByte(EM7180_ADDRESS, EM7180_ParamAcknowledge);
  }
`

**Comment by gregtomasch** [comment]
This is not general behavior, this seems to be a problem with an individual unit...

**Comment by gregtomasch** [comment]
Defective unit, not a general issue...
